
export const oneTime = [
  { date: '2017-01-02', cost: '1290', description: 'Fitbit', service: 'Siba', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-01-02', cost: '349', description: 'Ledlist', service: 'Jula', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-01-02', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-02', cost: '112.1', description: 'PS3-spel', service: 'Playstation Plus', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-01-02', cost: '63', description: 'PS3-spel', service: 'Playstation Plus', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-01-04', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-09', cost: '129', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-09', cost: '69', description: 'Lunch ', service: 'McDonalds', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-10', cost: '201.88', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-01-10', cost: '178', description: 'Mobilväska', service: 'Fyndiq', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-01-11', cost: '85', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-13', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-16', cost: '320', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-18', cost: '274.12', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-01-18', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-20', cost: '360', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-23', cost: '847.54', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: '', category: 2, recurrent: '' },
  { date: '2017-01-23', cost: '119.8', description: 'Div. elektronik', service: 'Kjell & Company', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-01-25', cost: '200', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-26', cost: '170', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-26', cost: '65', description: 'PS3-spel', service: 'Playstation Plus', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-01-26', cost: '60', description: 'Mat', service: 'Häggviks Livs', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-01-27', cost: '80', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-30', cost: '280', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-01-30', cost: '113', description: 'Mat', service: 'ICA', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-01-31', cost: '452.69', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-01', cost: '379.38', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-01', cost: '219.4', description: 'Grenkontakter', service: 'Jula', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-02-02', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-06', cost: '990', description: 'Elektronik', service: 'Elgiganten', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-02-06', cost: '338.79', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-06', cost: '240', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-06', cost: '153.9', description: 'Ljudbok', service: 'Audible', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-02-10', cost: '60', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-13', cost: '660', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-13', cost: '159.65', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-15', cost: '407', description: 'Porto Tradera', service: 'Posten', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-02-15', cost: '208', description: 'Köksgrejer', service: 'Inreda 24H', type: 'oneTime', comment: '', category: 11, recurrent: '' },
  { date: '2017-02-16', cost: '85', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-16', cost: '82', description: 'Mat', service: 'Baristo Coffee', type: 'oneTime', comment: '', category: 6, recurrent: '' },
  { date: '2017-02-17', cost: '320', description: 'Mat', service: 'ICA Kvantum Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-20', cost: '308.7', description: 'Reseladdare', service: 'Jula', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-02-20', cost: '285', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-20', cost: '219', description: 'Kattsand', service: 'Grizzly', type: 'oneTime', comment: '', category: 10, recurrent: '' },
  { date: '2017-02-20', cost: '200', description: 'Pendeltåg', service: 'Sl.se', type: 'oneTime', comment: '', category: 9, recurrent: '' },
  { date: '2017-02-20', cost: '99.8', description: 'Kabelkanal', service: 'Jula', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-02-21', cost: '2072', description: 'Köksgrejer', service: 'Ikea', type: 'oneTime', comment: '', category: 11, recurrent: '' },
  { date: '2017-02-21', cost: '189.6', description: 'Lampor', service: 'Jula', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-02-21', cost: '158.28', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-22', cost: '159', description: 'Porto Tradera', service: 'Posten', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-02-22', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-24', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-27', cost: '7124', description: 'Köksgrejer, möbler', service: 'Ikea', type: 'oneTime', comment: '', category: 11, recurrent: '' },
  { date: '2017-02-27', cost: '330', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-02-27', cost: '182', description: 'Taxi', service: 'Taxi', type: 'oneTime', comment: '', category: 9, recurrent: '' },
  { date: '2017-02-28', cost: '616.14', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-02-28', cost: '480.03', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: '', category: 2, recurrent: '' },
  { date: '2017-03-01', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-03', cost: '706', description: 'Nexa 433Mhz-prylar', service: 'Mobilkoden', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-03-03', cost: '205', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-06', cost: '272.03', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-03-06', cost: '254.7', description: 'Testpenna, strömbrytare', service: 'Jula', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-03-06', cost: '200', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-06', cost: '158.69', description: 'Ljudbok', service: 'Audible', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-03-06', cost: '158', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-03-06', cost: '33', description: 'Mat', service: 'ICA', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-03-07', cost: '118', description: 'Lunch ', service: 'McDonalds', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-08', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-09', cost: '40', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-10', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-13', cost: '527.6', description: 'Div. bygg', service: 'Jula', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-03-13', cost: '360', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-13', cost: '299', description: 'T-tröjor', service: 'Zalando', type: 'oneTime', comment: '', category: 11, recurrent: '' },
  { date: '2017-03-15', cost: '806.35', description: 'Bensin', service: 'OKQ8', type: 'oneTime', comment: '', category: 2, recurrent: '' },
  { date: '2017-03-15', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-16', cost: '119.8', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-17', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-20', cost: '2166.8', description: 'Mutterdragare, cementblandare', service: 'Jula', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-03-20', cost: '280', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-21', cost: '379', description: 'Skruvdragare', service: 'K-rauta', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-03-22', cost: '354.66', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-03-22', cost: '130', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-24', cost: '250', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-27', cost: '240', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-03-27', cost: '85', description: 'Lunch ', service: 'Matmagazinet', type: 'oneTime', comment: '', category: 6, recurrent: '' },
  { date: '2017-03-27', cost: '55.37', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: '', category: 2, recurrent: '' },
  { date: '2017-03-28', cost: '226.98', description: 'Arduino/Pi-prylar', service: 'BangGood', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-03-28', cost: '60.92', description: 'Arduino/Pi-prylar', service: 'GearBeast', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-03', cost: '2407', description: 'Compressor, skruvdragare, etikettskrivare', service: 'Compressor, skruvdragare, etikettskrivare', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-03', cost: '240', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-03', cost: '200', description: 'Pendeltåg', service: 'Sl.se', type: 'oneTime', comment: '', category: 9, recurrent: '' },
  { date: '2017-04-03', cost: '135.49', description: 'Medicin', service: 'Apoteket', type: 'oneTime', comment: '', category: 5, recurrent: '' },
  { date: '2017-04-03', cost: '109.9', description: 'Div. elektronik', service: 'Kjell & Company', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-03', cost: '104.48', description: 'Elektronik', service: 'Ali Express', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-03', cost: '99', description: 'Lunch', service: 'Wok och Sushi', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-03', cost: '37.5', description: 'Mat', service: 'ICA Norrviken', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-04', cost: '342.6', description: 'Mat', service: 'ICA Kvantum Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-04', cost: '320', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-05', cost: '156.79', description: 'Ljudbok', service: 'Audible', type: 'oneTime', comment: '', category: 7, recurrent: '' },
  { date: '2017-04-05', cost: '70', description: 'Elektronik', service: 'Tradera', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-06', cost: '160', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-06', cost: '80', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '1358.5', description: 'Målargrejer', service: 'Jula', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-04-10', cost: '330', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '230', description: 'Bärs', service: 'Sollentuna Bowlinghall', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '200', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '189', description: 'Bärs', service: 'Sollentuna Bowlinghall', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '126', description: 'Bärs', service: 'Sollentuna Bowlinghall', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '119.8', description: 'Bärs', service: 'Sollentuna Bowlinghall', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-10', cost: '100', description: 'Handdukar', service: 'Jysk', type: 'oneTime', comment: '', category: 11, recurrent: '' },
  { date: '2017-04-10', cost: '95', description: 'Mat', service: '3 Måltider', type: 'oneTime', comment: '', category: 6, recurrent: '' },
  { date: '2017-04-13', cost: '1470.1', description: 'Verktyg och bygg', service: 'Bauhause', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-04-13', cost: '595.2', description: 'En back bärs', service: 'Systembolaget', type: 'oneTime', comment: '', category: 6, recurrent: '' },
  { date: '2017-04-13', cost: '95.1', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-18', cost: '816', description: 'Mat', service: 'Thaibutiken Sollentuna C', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-18', cost: '479.97', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-18', cost: '144.4', description: 'Mat', service: 'COOP Nära Berg', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-18', cost: '90', description: 'Lunch', service: 'Pong Sollentuna', type: 'oneTime', comment: '', category: 6, recurrent: '' },
  { date: '2017-04-24', cost: '526.87', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-24', cost: '200', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-24', cost: '40', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-25', cost: '358', description: 'Kattsand', service: 'Grizzly', type: 'oneTime', comment: '', category: 10, recurrent: '' },
  { date: '2017-04-25', cost: '148.95', description: 'Verktyg och bygg', service: 'Bauhause', type: 'oneTime', comment: '', category: 1, recurrent: '' },
  { date: '2017-04-26', cost: '492.63', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: '', category: 4, recurrent: '' },
  { date: '2017-04-26', cost: '423', description: 'Batteri till Samsungpaddan', service: 'Teknikdelar', type: 'oneTime', comment: '', category: 8, recurrent: '' },
  { date: '2017-04-27', cost: '240', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: '', category: 3, recurrent: '' },
  { date: '2017-04-28', cost: '560.72', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: '', category: 2, recurrent: '' },
  { date: '2017-05-02', cost: '213', description: 'Lim', service: 'Bauhause', type: 'oneTime', comment: 'Bauhause', category: 1, recurrent: '' },
  { date: '2017-05-02', cost: '208', description: 'Impregnering, Lim', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-05-03', cost: '790', description: 'Bensin 95', service: 'Circle K', type: 'oneTime', comment: 'Circkle K, 55L', category: 2, recurrent: '' },
  { date: '2017-05-04', cost: '27', description: 'Försäljning SL400', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 0, recurrent: '' },
  { date: '2017-05-04', cost: '100', description: 'Kebab med öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-04', cost: '49', description: 'Vinkelchuck', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-05-05', cost: '94.5', description: 'Vaxör', service: 'Apoteket', type: 'oneTime', comment: 'Apoteket', category: 5, recurrent: '' },
  { date: '2017-05-09', cost: '200', description: '4 öl + köttbullar', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-09', cost: '48', description: 'Mat', service: 'Närlivs Häggvik', type: 'oneTime', comment: 'Hägges Livs', category: 4, recurrent: '' },
  { date: '2017-05-11', cost: '120', description: '3 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-11', cost: '95', description: 'Sushi', service: '3 Måltider', type: 'oneTime', comment: '3 Måltider', category: 6, recurrent: '' },
  { date: '2017-05-14', cost: '1182', description: 'Plex Pass Lifetime ', service: 'Plex', type: 'oneTime', comment: 'MasterCard', category: 7, recurrent: '' },
  { date: '2017-05-15', cost: '598', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP', category: 4, recurrent: '' },
  { date: '2017-05-15', cost: '2882', description: 'Multiverktyg, batteri, laddare', service: 'Bauhause', type: 'oneTime', comment: 'Bauhause', category: 1, recurrent: '' },
  { date: '2017-05-15', cost: '267', description: '1 back öl', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-05-15', cost: '120', description: 'Bärs', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-16', cost: '94', description: 'Mobilabonnemang, byte', service: 'Tele2', type: 'oneTime', comment: 'Tele2', category: 7, recurrent: '' },
  { date: '2017-05-18', cost: '280', description: 'Bärs + mat', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-21', cost: '465.7', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-05-22', cost: '100', description: 'Mutter, dush', service: 'K-Rauta', type: 'oneTime', comment: 'K-Rauta', category: 1, recurrent: '' },
  { date: '2017-05-22', cost: '109', description: 'Lunch, Sollentuna', service: 'Basilica', type: 'oneTime', comment: 'Basilica', category: 6, recurrent: '' },
  { date: '2017-05-22', cost: '267', description: '1 back öl', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-05-22', cost: '399', description: 'Bluetooth Sony SBH-20', service: 'Netonnet', type: 'oneTime', comment: 'Netonnet', category: 8, recurrent: '' },
  { date: '2017-05-22', cost: '466', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP', category: 4, recurrent: '' },
  { date: '2017-05-23', cost: '200', description: 'Öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-05-24', cost: '456.27', description: 'Bensin 95', service: 'OKQ8', type: 'oneTime', comment: 'OKQ8', category: 2, recurrent: '' },
  { date: '2017-05-24', cost: '300', description: 'ELM327 OBD2 Bluetooth', service: 'Teknikmagasinet', type: 'oneTime', comment: 'Teknikmagasinet', category: 8, recurrent: '' },
  { date: '2017-05-25', cost: '3688.95', description: 'Veranda', service: 'Bauhause', type: 'oneTime', comment: 'Bauhause Kalmar', category: 1, recurrent: '' },
  { date: '2017-05-25', cost: '93.8', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-05-25', cost: '360.1', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-05-26', cost: '313.8', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-05-26', cost: '1919.05', description: 'Veranda', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-05-26', cost: '399', description: '12 GB bredband Öland', service: 'Telia', type: 'oneTime', comment: 'Telia', category: 7, recurrent: '' },
  { date: '2017-05-27', cost: '498.7', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-05-27', cost: '1429.28', description: 'Veranda', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-05-29', cost: '1661.7', description: 'Veranda', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-05-30', cost: '337.6', description: 'Veranda', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-05-30', cost: '40', description: 'Motorsågsolja', service: 'Löttorps Skog & Träd', type: 'oneTime', comment: 'Löttorps Skog & Träd', category: 1, recurrent: '' },
  { date: '2017-05-30', cost: '1990', description: 'Motorsåg', service: 'Löttorps Skog & Träd', type: 'oneTime', comment: 'Löttorps Skog & Träd', category: 1, recurrent: '' },
  { date: '2017-06-05', cost: '108.9', description: 'Veranda', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-06-04', cost: '467.9', description: 'Kattsand', service: 'Grizzly', type: 'oneTime', comment: 'Grizzly Häggvik', category: 10, recurrent: '' },
  { date: '2017-06-04', cost: '328', description: 'Nokia 150 Dual-Sim White', service: 'Webhallen', type: 'oneTime', comment: 'Webhallen', category: 8, recurrent: '' },
  { date: '2017-06-04', cost: '899', description: 'Bakmaskin', service: 'Komplett', type: 'oneTime', comment: 'Komplett', category: 8, recurrent: '' },
  { date: '2017-06-04', cost: '49', description: 'Mat', service: 'Ringarums Värdshus', type: 'oneTime', comment: 'Ringarums Vardshus', category: 6, recurrent: '' },
  { date: '2017-06-04', cost: '237.3', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-06-04', cost: '806.16', description: 'Bensin 95', service: 'OKQ8', type: 'oneTime', comment: 'OKQ8', category: 2, recurrent: '' },
  { date: '2017-06-07', cost: '854.5', description: 'Byxor, sekatör, stor vinkel, halogen', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-06-08', cost: '142', description: 'Blodtrycksmedicin + plackers', service: 'Apotek Hjärtat', type: 'oneTime', comment: '', category: 5, recurrent: '' },
  { date: '2017-06-08', cost: '50', description: 'Comviq kontant extra', service: 'Comviq', type: 'oneTime', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-06-08', cost: '105.98', description: '2 extra armband fitbit charge 2', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay, UK', category: 8, recurrent: '' },
  { date: '2017-06-08', cost: '95.9', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-06-09', cost: '280', description: '7 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-06-10', cost: '43', description: 'Korv med pomfritt', service: 'Vaxholm', type: 'oneTime', comment: 'Vaxholm', category: 6, recurrent: '' },
  { date: '2017-06-10', cost: '125', description: 'Cinderella', service: 'Vaxholmsbolaget', type: 'oneTime', comment: 'Vaxholmsbolaget', category: 9, recurrent: '' },
  { date: '2017-06-13', cost: '210', description: 'Pizza + 3 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-06-14', cost: '1170', description: 'USB-laddare och grenuttag', service: 'Deltaco', type: 'oneTime', comment: 'Deltaco', category: 8, recurrent: '' },
  { date: '2017-06-16', cost: '100', description: '5 små dynor', service: 'Jysk', type: 'oneTime', comment: 'Jysk', category: 11, recurrent: '' },
  { date: '2017-06-16', cost: '358.6', description: 'Hammarlack, bryne, häftklammer', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-06-16', cost: '304', description: 'Avslutsfaktur mobil data/tele', service: 'Tele2', type: 'oneTime', comment: 'Tele 2', category: 7, recurrent: '' },
  { date: '2017-06-19', cost: '120', description: '3 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-06-19', cost: '191.52', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-06-19', cost: '499', description: 'Kattmat 10 kg', service: 'Grizzly', type: 'oneTime', comment: 'Grizzly', category: 10, recurrent: '' },
  { date: '2017-06-19', cost: '266.4', description: '1 back ÖL Flat tire', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-06-19', cost: '793.54', description: 'Bensin 95', service: 'Circle K', type: 'oneTime', comment: 'Cirkle K', category: 2, recurrent: '' },
  { date: '2017-06-21', cost: '266.4', description: '1 back ÖL Flat tire', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-06-20', cost: '320', description: '8 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-06-21', cost: '993.7', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-06-21', cost: '2 695,0', description: 'Playstation 4', service: 'Sweden Mobile', type: 'oneTime', comment: 'Sweden Mobile', category: 8, recurrent: '' },
  { date: '2017-06-21', cost: '336', description: 'Playstation+ 1 år', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-06-26', cost: '169.9', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-06-26', cost: '64.2', description: '', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-06-29', cost: '237.6', description: 'En back öl', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-06-30', cost: '320', description: '8 öl', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-06-30', cost: '86.7', description: '', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-07-01', cost: '432.2', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-07-01', cost: '173.4', description: 'The Witcher 3', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-07-02', cost: '50', description: 'Koaxialkabel kort', service: 'Teknikmagasinet', type: 'oneTime', comment: 'Teknikmagasinet', category: 8, recurrent: '' },
  { date: '2017-07-02', cost: '347.75', description: 'Kattnät till bilen', service: 'K-rauta', type: 'oneTime', comment: 'K-rauta', category: 1, recurrent: '' },
  { date: '2017-07-02', cost: '833.64', description: 'Bensin', service: 'OKQ8', type: 'oneTime', comment: 'OK-Q8', category: 2, recurrent: '' },
  { date: '2017-07-05', cost: '171', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-07-11', cost: '430', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-07-14', cost: '169', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-07-16', cost: '122', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-07-17', cost: '255', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-07-17', cost: '121', description: '12 Falkon', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-07-19', cost: '401', description: 'Assassins Creed® IV Black Flag, No Mans Sky, The Talos Principle, L.A. Noire', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-07-20', cost: '277.1', description: 'Mat', service: 'City Gross', type: 'oneTime', comment: 'City Gross', category: 4, recurrent: '' },
  { date: '2017-07-20', cost: '739.66', description: 'Mat (bunkra kött)', service: 'City Gross', type: 'oneTime', comment: 'City Gross', category: 4, recurrent: '' },
  { date: '2017-07-20', cost: '785.9', description: 'Stållina, fästen, olja', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-07-20', cost: '442.6', description: 'Korgar, handskar, fogspruta', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2017-07-20', cost: '1180', description: 'Krokar och burkar', service: 'Ikea', type: 'oneTime', comment: 'IKEA', category: 11, recurrent: '' },
  { date: '2017-07-20', cost: '69', description: 'Brunch', service: 'Ikea', type: 'oneTime', comment: 'IKEA', category: 6, recurrent: '' },
  { date: '2017-07-20', cost: '73', description: 'Masktabletter', service: 'Apoteket', type: 'oneTime', comment: 'APOTEKET', category: 5, recurrent: '' },
  { date: '2017-07-22', cost: '250.81', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-07-22', cost: '278.4', description: 'Virke hall', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygh', category: 1, recurrent: '' },
  { date: '2017-07-24', cost: '216.8', description: 'The Witness, INSIDE, Cosmic Star Heroine', service: 'Playstation Plus', type: 'oneTime', comment: 'PSN', category: 7, recurrent: '' },
  { date: '2017-07-28', cost: '255.71', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-08-01', cost: '295.66', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-08-03', cost: '686.9', description: 'Isolering, torv till kompost', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2017-08-03', cost: '229.4', description: 'Diverse', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-08-03', cost: '250', description: 'Dyna liggstol turkos', service: 'Jysk', type: 'oneTime', comment: 'Jysk', category: 11, recurrent: '' },
  { date: '2017-08-03', cost: '1241', description: 'Lådor och burkar', service: 'Ikea', type: 'oneTime', comment: 'Ikea', category: 11, recurrent: '' },
  { date: '2017-08-03', cost: '301.25', description: 'Mat', service: 'City Gross', type: 'oneTime', comment: 'City Gross', category: 4, recurrent: '' },
  { date: '2017-08-04', cost: '1119.32', description: 'Latrinkompost', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-08-07', cost: '354', description: '2 vindunkar', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-08-10', cost: '401', description: 'Mat', service: 'Harö Livs', type: 'oneTime', comment: 'Harö livs', category: 4, recurrent: '' },
  { date: '2017-08-08', cost: '14.7', description: 'Mat', service: 'Coop Vaxholm', type: 'oneTime', comment: 'Coop Vaxholm', category: 4, recurrent: '' },
  { date: '2017-08-07', cost: '819.4', description: 'Bensin', service: 'Preem', type: 'oneTime', comment: 'Preem', category: 2, recurrent: '' },
  { date: '2017-08-08', cost: '145', description: 'Vaxholmsbåt', service: 'Cinderella', type: 'oneTime', comment: 'Cinderella', category: 9, recurrent: '' },
  { date: '2017-08-07', cost: '383.1', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-10', cost: '500', description: 'Parkeringsböter', service: 'Polisen', type: 'oneTime', comment: 'Polisen', category: 0, recurrent: '' },
  { date: '2017-08-11', cost: '500', description: 'Parkeringsböter', service: 'Polisen', type: 'oneTime', comment: 'Polisen', category: 0, recurrent: '' },
  { date: '2017-08-14', cost: '385.6', description: 'Snabbtvingar, kontakter', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-08-14', cost: '147.81', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-16', cost: '383.23', description: 'Mat', service: 'ICA Maxi', type: 'oneTime', comment: 'ICA Maxi', category: 4, recurrent: '' },
  { date: '2017-08-18', cost: '159.95', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-18', cost: '47.25', description: 'Mat', service: 'ICA Maxi', type: 'oneTime', comment: 'ICA Maxi', category: 4, recurrent: '' },
  { date: '2017-08-23', cost: '402.69', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-24', cost: '222.47', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-25', cost: '525', description: 'Tandundersökning, Liang Ma, Rotebro', service: 'Folktandvården', type: 'oneTime', comment: 'Liang Ma, Rotebro', category: 5, recurrent: '' },
  { date: '2017-08-25', cost: '96', description: 'Fitbitarmband', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay, UK', category: 8, recurrent: '' },
  { date: '2017-08-25', cost: '122', description: 'Munskölj 100 dagar', service: 'Apotek Hjärtat', type: 'oneTime', comment: 'Apoteket Hjärtat', category: 5, recurrent: '' },
  { date: '2017-08-29', cost: '200', description: '5 bärs', service: 'Hägges', type: 'oneTime', comment: 'Hägges', category: 3, recurrent: '' },
  { date: '2017-08-25', cost: '879', description: 'Kök: Burkar, knivställ mm.', service: 'Ikea', type: 'oneTime', comment: 'IKEA', category: 11, recurrent: '' },
  { date: '2017-08-25', cost: '29.95', description: 'Trådsprättare', service: 'Jysk', type: 'oneTime', comment: 'Jysk', category: 11, recurrent: '' },
  { date: '2017-08-28', cost: '314.81', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-08-29', cost: '406.1', description: 'Kattlucka, sele, leksaker', service: 'Zooplus', type: 'oneTime', comment: 'Zooplus', category: 10, recurrent: '' },
  { date: '2017-09-01', cost: '633.12', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: 'Circle K', category: 2, recurrent: '' },
  { date: '2017-09-01', cost: '69', description: 'Rosevin', service: 'Systembolaget', type: 'oneTime', comment: 'Systemet', category: 3, recurrent: '' },
  { date: '2017-09-03', cost: '129.3', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop', category: 4, recurrent: '' },
  { date: '2017-09-02', cost: '24.74', description: 'Glasögon, ATTiny', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay, UK', category: 8, recurrent: '' },
  { date: '2017-09-05', cost: '156.56', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-09-05', cost: '119', description: 'Deus Ex', service: 'Playstation Plus', type: 'oneTime', comment: 'PS4', category: 7, recurrent: '' },
  { date: '2017-09-04', cost: '297.9', description: 'Diverse', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-09-06', cost: '399', description: 'Bredband Öland 12Gb', service: 'Telia', type: 'oneTime', comment: 'Telia', category: 7, recurrent: '' },
  { date: '2017-09-07', cost: '466.14', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-09-07', cost: '396.35', description: 'Formplyfa', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-09-12', cost: '1091', description: 'Lådor till kök', service: 'Ikea', type: 'oneTime', comment: 'IKEA', category: 11, recurrent: '' },
  { date: '2017-09-12', cost: '2265.6', description: 'Tillbehör utedusch', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-09-12', cost: '394.3', description: 'Tillbehör utedusch', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2017-09-12', cost: '283.9', description: 'Kökshyllor', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2017-09-12', cost: '999', description: 'Gångskor', service: 'XXL Sport', type: 'oneTime', comment: 'XXL Sport', category: 11, recurrent: '' },
  { date: '2017-09-12', cost: '726.52', description: 'Mat', service: 'City Gross', type: 'oneTime', comment: 'City Gross', category: 4, recurrent: '' },
  { date: '2017-09-12', cost: '139.92', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-09-12', cost: '764.87', description: 'Bensin', service: 'OKQ8', type: 'oneTime', comment: 'OKQ8', category: 2, recurrent: '' },
  { date: '2017-09-13', cost: '69', description: 'Rayman legends', service: 'Playstation Plus', type: 'oneTime', comment: 'Playstation', category: 7, recurrent: '' },
  { date: '2017-09-15', cost: '286', description: 'Piston head', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-09-15', cost: '517.26', description: 'Tillbehör utedusch', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-09-15', cost: '317.86', description: 'Tillbehör utedusch', service: 'Löttorps Bygg', type: 'oneTime', comment: 'Löttorps Bygg', category: 1, recurrent: '' },
  { date: '2017-09-15', cost: '235.11', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-09-21', cost: '216.48', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-09-25', cost: '1473', description: 'Fritidsbyxa, sockor, mössa', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-09-25', cost: '359.23', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-09-25', cost: '59', description: 'Handskar', service: 'Swedish Agro', type: 'oneTime', comment: 'Swedish Agro', category: 1, recurrent: '' },
  { date: '2017-09-25', cost: '114.9', description: 'Spänningsmätare', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2017-09-25', cost: '69', description: 'Lunch ', service: 'Ikea', type: 'oneTime', comment: 'Ikea', category: 6, recurrent: '' },
  { date: '2017-09-25', cost: '285.6', description: 'Pistonhead back', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-09-25', cost: '862', description: 'Diverse Öland', service: 'Ikea', type: 'oneTime', comment: 'Ikea', category: 11, recurrent: '' },
  { date: '2017-09-28', cost: '60', description: 'Sopsäckar till dass', service: 'Löttorps bygg', type: 'oneTime', comment: 'Löttorps bygg', category: 1, recurrent: '' },
  { date: '2017-09-28', cost: '160', description: 'Fasskena, bygel', service: 'Åkebo El', type: 'oneTime', comment: 'Åkebo el', category: 1, recurrent: '' },
  { date: '2017-09-29', cost: '169.71', description: 'Reglar dusch', service: 'Löttorps bygg', type: 'oneTime', comment: 'Löttorps bygg', category: 1, recurrent: '' },
  { date: '2017-09-29', cost: '229.6', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-09-29', cost: '100', description: 'Kontaktskydd', service: 'Eldirekt.se', type: 'oneTime', comment: 'Eldirekt.se', category: 1, recurrent: '' },
  { date: '2017-10-02', cost: '232', description: 'Långärmad tröja 2 st', service: 'Zalando', type: 'oneTime', comment: 'Zalando', category: 11, recurrent: '' },
  { date: '2017-10-03', cost: '89.1', description: 'The sexy brutale', service: 'Playstation Plus', type: 'oneTime', comment: 'Playstation Plus', category: 7, recurrent: '' },
  { date: '2017-10-05', cost: '722.97', description: 'Kistor vardagsrum', service: 'Löttorps bygg', type: 'oneTime', comment: 'Löttorps bygg', category: 1, recurrent: '' },
  { date: '2017-10-05', cost: '461.28', description: 'Mat', service: 'ICA Löttorp', type: 'oneTime', comment: 'ICA Löttorp', category: 4, recurrent: '' },
  { date: '2017-10-05', cost: '212.2', description: 'Medicin blodtryck, Frontline', service: 'Apoteket', type: 'oneTime', comment: 'Apoteket', category: 5, recurrent: '' },
  { date: '2017-10-05', cost: '34.9', description: 'Krokar tvättlina', service: 'Löttorps bygg', type: 'oneTime', comment: 'Löttorps bygg', category: 1, recurrent: '' },
  { date: '2017-10-05', cost: '37', description: 'Android Callistics Pro', service: 'Google', type: 'oneTime', comment: 'Google', category: 7, recurrent: '' },
  { date: '2017-10-11', cost: '213', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-10-12', cost: '108', description: 'Pannlampor', service: 'eBay UK', type: 'oneTime', comment: 'eBay UK', category: 8, recurrent: '' },
  { date: '2017-10-15', cost: '222', description: 'Spel PS4', service: 'Playstation Plus', type: 'oneTime', comment: 'PlayStation', category: 7, recurrent: '' },
  { date: '2017-10-17', cost: '85.39', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-10-17', cost: '254.94', description: 'Mat', service: 'ICA Källa', type: 'oneTime', comment: 'ICA Källa', category: 4, recurrent: '' },
  { date: '2017-10-17', cost: '138', description: 'Glykol', service: 'OKQ8', type: 'oneTime', comment: 'OKQ8 Löttorp', category: 2, recurrent: '' },
  { date: '2017-10-19', cost: '675.08', description: 'Bensin', service: 'OKQ8', type: 'oneTime', comment: 'OKQ8', category: 2, recurrent: '' },
  { date: '2017-10-19', cost: '39', description: 'Smörgås', service: 'Ringarums Värdshus', type: 'oneTime', comment: 'Ringarum', category: 6, recurrent: '' },
  { date: '2017-10-19', cost: '227.08', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-10-19', cost: '1216.8', description: 'Kläder', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-10-20', cost: '1568.8', description: 'Matberedare Bosch', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-10-20', cost: '276', description: 'En back Flat Tire', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-10-20', cost: '90.95', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-10-20', cost: '799', description: 'Hushållsassistent', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-10-20', cost: '194', description: 'Oddworld, Fallout 4', service: 'Playstation Plus', type: 'oneTime', comment: 'PlayStation', category: 7, recurrent: '' },
  { date: '2017-10-20', cost: '754.1', description: 'Kattmat', service: 'Zooplus', type: 'oneTime', comment: 'Zooplus', category: 10, recurrent: '' },
  { date: '2017-10-22', cost: '230.72', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-10-22', cost: '199.8', description: 'Duschslang', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-10-22', cost: '249.7', description: 'Poligrip, rörtång', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 1, recurrent: '' },
  { date: '2017-10-22', cost: '504', description: 'Kryddburkar', service: 'Ikea', type: 'oneTime', comment: 'Ikea', category: 11, recurrent: '' },
  { date: '2017-10-24', cost: '735', description: 'Ta bort tandsten', service: 'Folktandvården', type: 'oneTime', comment: 'Folktandvården', category: 5, recurrent: '' },
  { date: '2017-10-26', cost: '232.98', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-10-26', cost: '767.4', description: 'Mat', service: 'ICA Häggvik', type: 'oneTime', comment: 'ICA Häggvik', category: 4, recurrent: '' },
  { date: '2017-11-01', cost: '1490', description: 'Frysbox', service: 'Elgiganten', type: 'oneTime', comment: 'Elgiganten', category: 7, recurrent: '' },
  { date: '2017-11-02', cost: '223.35', description: 'Mat', service: 'ICA Häggvik', type: 'oneTime', comment: 'ICA Häggvik', category: 4, recurrent: '' },
  { date: '2017-11-03', cost: '676.8', description: 'Lampor', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-11-03', cost: '822.27', description: 'Bensin', service: 'Circle K', type: 'oneTime', comment: 'Circle K', category: 2, recurrent: '' },
  { date: '2017-11-03', cost: '171.5', description: 'E-bok Life 3.0', service: 'Amazon', type: 'oneTime', comment: 'Amazon', category: 7, recurrent: '' },
  { date: '2017-11-09', cost: '82', description: 'Mat', service: 'McDonalds', type: 'oneTime', comment: 'McDonalds', category: 6, recurrent: '' },
  { date: '2017-11-10', cost: '299', description: 'Raspberry PI 3 B', service: 'Power', type: 'oneTime', comment: 'Power', category: 8, recurrent: '' },
  { date: '2017-11-10', cost: '200', description: 'Reskassa', service: 'Sl.se', type: 'oneTime', comment: 'Sl.se', category: 9, recurrent: '' },
  { date: '2017-11-10', cost: '560.56', description: 'Mat', service: 'ICA Häggvik', type: 'oneTime', comment: 'ICA Häggvik', category: 4, recurrent: '' },
  { date: '2017-11-13', cost: '285.6', description: 'En back Pistonhead', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-11-17', cost: '98', description: '2 öl', service: 'Hamilton Bar & Res', type: 'oneTime', comment: 'Hamilton Bar & Res', category: 3, recurrent: '' },
  { date: '2017-11-17', cost: '64', description: '1 öl', service: 'Paddys', type: 'oneTime', comment: 'Paddys', category: 3, recurrent: '' },
  { date: '2017-11-21', cost: '665.27', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'Coop Häggvik', category: 4, recurrent: '' },
  { date: '2017-11-25', cost: '499', description: 'Byxor', service: 'Dressman', type: 'oneTime', comment: 'Dressman', category: 11, recurrent: '' },
  { date: '2017-11-25', cost: '22.89', description: 'DVI to HDMI adapter', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay UK', category: 8, recurrent: '' },
  { date: '2017-11-25', cost: '100.6', description: 'DYI-prylar', service: 'GearBeast', type: 'oneTime', comment: 'GearBeast', category: 8, recurrent: '' },
  { date: '2017-11-27', cost: '471.87', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP Häggvik', category: 4, recurrent: '' },
  { date: '2017-12-01', cost: '89.9', description: 'Lösglasögon', service: 'Clas Ohlson', type: 'oneTime', comment: 'Clas Ohlson', category: 1, recurrent: '' },
  { date: '2017-12-01', cost: '69', description: '1 Öl', service: 'Hamilton Bar & Res', type: 'oneTime', comment: 'Hamilton Bar & Res', category: 3, recurrent: '' },
  { date: '2017-12-01', cost: '87', description: '3 öl', service: 'Paddys', type: 'oneTime', comment: 'Paddys', category: 3, recurrent: '' },
  { date: '2017-12-07', cost: '586.16', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP Häggvik', category: 4, recurrent: '' },
  { date: '2017-12-07', cost: '219', description: 'Kattsand', service: 'Arken Zoo', type: 'oneTime', comment: 'Arken Zoo', category: 10, recurrent: '' },
  { date: '2017-12-09', cost: '215.34', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP Häggvik', category: 4, recurrent: '' },
  { date: '2017-12-10', cost: '640', description: 'Tomterockers', service: 'Försvarsgården Häggvik', type: 'oneTime', comment: 'Försvarsgården Häggvik', category: 3, recurrent: '' },
  { date: '2017-12-11', cost: '345.74', description: 'Frontend Masters', service: 'Frontendmasters.com', type: 'oneTime', comment: 'Frontendmasters.com', category: 7, recurrent: '' },
  { date: '2017-12-15', cost: '66', description: 'Mat', service: 'McDonalds', type: 'oneTime', comment: 'McDonalds', category: 3, recurrent: '' },
  { date: '2017-12-17', cost: '218.8', description: 'Kläder, duschslang mamma', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-12-17', cost: '802.52', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP Häggvik', category: 4, recurrent: '' },
  { date: '2017-12-20', cost: '22.7', description: '3x Aluminum Heatsink', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay UK', category: 8, recurrent: '' },
  { date: '2017-12-21', cost: '169.7', description: 'Handskar + godis', service: 'Jula', type: 'oneTime', comment: 'Jula', category: 11, recurrent: '' },
  { date: '2017-12-21', cost: '176', description: '2 glögg', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-12-29', cost: '524.5', description: 'Glögg + Pistonhead', service: 'Systembolaget', type: 'oneTime', comment: 'Systembolaget', category: 3, recurrent: '' },
  { date: '2017-12-30', cost: '110', description: 'Bio', service: 'Vaxholms Bio', type: 'oneTime', comment: 'Vaxholms Bio', category: 0, recurrent: '' },
  { date: '2018-01-02', cost: '22', description: 'Trängselskatt', service: 'Vägverket', type: 'oneTime', comment: 'Vägverket', category: 2, recurrent: '' },
  { date: '2018-01-02', cost: '748.61', description: 'Mat', service: 'Coop Häggvik', type: 'oneTime', comment: 'COOP Häggvik', category: 4, recurrent: '' },
  { date: '2018-01-02', cost: '899', description: 'Headset Sony MDR-XB950B1', service: 'Netonnet', type: 'oneTime', comment: 'Netonnet', category: 8, recurrent: '' },
  { date: '2018-01-02', cost: '11.5', description: 'Heatsink tejp', service: 'Ebay UK', type: 'oneTime', comment: 'Ebay UK', category: 8, recurrent: '' },
  { date: '2018-01-03', cost: '188.95', description: 'Krandusch till Mamma', service: 'Bauhause', type: 'oneTime', comment: 'Bauhaus', category: 1, recurrent: '' },
  { date: '2018-01-03', cost: '63.45', description: 'Mat', service: 'City Gross', type: 'oneTime', comment: 'City Gross Häggvik', category: 4, recurrent: '' },
  { date: '2018-01-03', cost: '899', description: 'Walkingskor Salamon Wentwood GTX', service: 'Intersport', type: 'oneTime', comment: 'Intersport', category: 11, recurrent: '' },
  { date: '2018-01-05', cost: '73', description: 'Mat', service: 'Thaibutiken Sollentuna C', type: 'oneTime', comment: 'Thaibutiken Sollentuna C', category: 4, recurrent: '' },
  { date: '2018-01-05', cost: '289', description: 'Logitech C270 HD', service: 'Netonnet', type: 'oneTime', comment: 'Netonnet', category: 8, recurrent: '' },
  { date: '2018-01-05', cost: '549', description: 'Logitech HD Pro Webcam C920', service: 'Netonnet', type: 'oneTime', comment: 'Netonnet', category: 8, recurrent: '' },
  { date: '2018-01-05', cost: '1074', description: 'Kläder', service: '4Work Yrkeskläder', type: 'oneTime', comment: '4Work Yrkeskläder', category: 11, recurrent: '' },
  { date: '2017-01-25', cost: '28.943', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-02-25', cost: '28.866', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-03-25', cost: '28.866', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-04-25', cost: '28.474', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-05-25', cost: '28.866', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-06-25', cost: '28.866', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-07-25', cost: '18.354', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-08-25', cost: '17.743', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-09-25', cost: '4.173', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-10-25', cost: '4.309', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-11-25', cost: '3.738', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-12-25', cost: '4.29', description: 'Lön', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 100, recurrent: '' },
  { date: '2017-01-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-02-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-03-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-04-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-05-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-06-25', cost: '4000', description: 'Privat pensionssparande', service: 'Licencia', type: 'monthly', comment: 'Licencia', category: 101, recurrent: '' },
  { date: '2017-01-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-02-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-03-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-04-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-05-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-06-25', cost: '4000', description: 'Privat pensionssparande', service: 'SEB', type: 'monthly', comment: 'SEB', category: 15, recurrent: '' },
  { date: '2017-03-25', cost: '32', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-03-27', cost: '45', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-03-25', cost: '68', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-02-19', cost: '262', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-02-18', cost: '415', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-03-25', cost: '486', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
  { date: '2017-04-04', cost: '526', description: 'Skatteåterbäring', service: 'Skatteåterbäring', type: 'oneTime', comment: 'Skatteverket', category: 103, recurrent: '' },
  { date: '2017-02-12', cost: '829', description: 'Modelljärnväg', service: 'Tradera', type: 'oneTime', comment: 'Tradera', category: 102, recurrent: '' },
];

export const multipleTime = [
  { date: '2017-01-31', cost: '702', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-03-27', cost: '719', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-05-31', cost: '713', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-07-29', cost: '616', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-09-24', cost: '704', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-11-30', cost: '593', description: 'Sollentuna Energi', service: 'Sollentuna Energi', type: 'quartely', comment: '', category: 12, recurrent: '' },
  { date: '2017-01-01', cost: '2236', description: 'Hemförsäkring', service: 'Länsförsäkringar', type: 'yearly', comment: 'Länsförsäkringar', category: 13, recurrent: '' },
  { date: '2018-01-01', cost: '2263', description: 'Hemförsäkring', service: 'Länsförsäkringar', type: 'yearly', comment: 'Länsförsäkringar', category: 13, recurrent: '' },
  { date: '2017-11-01', cost: '3818', description: 'Bilförsäkring', service: 'Länsförsäkringar', type: 'yearly', comment: 'Länsförsäkringar', category: 13, recurrent: '' },
  { date: '2017-11-01', cost: '1278', description: 'Djurförsäkring', service: 'Länsförsäkringar/Agria', type: 'yearly', comment: 'Agria', category: 13, recurrent: '' },
  { date: '2017-04-26', cost: '99', description: 'DNS', service: 'Loopia', type: 'yearly', comment: 'Loopia', category: 7, recurrent: '' },
  { date: '2017-04-26', cost: '129', description: 'Domännamn', service: 'Loopia', type: 'yearly', comment: 'Loopia', category: 7, recurrent: '' },
  { date: '2017-08-07', cost: '108', description: 'LastPass', service: 'LastPass', type: 'yearly', comment: 'LastPass', category: 7, recurrent: '' },
  { date: '2017-07-01', cost: '288', description: 'Årskostnad kort', service: 'Nordea', type: 'yearly', comment: 'Nordea', category: 7, recurrent: '' },
  { date: '2017-08-16', cost: '395', description: 'Besiktning', service: 'Svensk bilprovning', type: 'yearly', comment: 'Svensk bilprovning', category: 2, recurrent: '' },
  { date: '2017-10-31', cost: '1950', description: 'Fordonsskatt', service: 'Transportstyrelsen', type: 'yearly', comment: 'Transportstyrelsen', category: 2, recurrent: '' },
  { date: '2017-01-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-02-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-03-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-04-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-05-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-06-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-07-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-08-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-09-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-10-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-11-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-12-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-01-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-02-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-03-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-04-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-05-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-06-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-07-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-08-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-09-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-10-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-11-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-12-01', cost: '12', description: 'Nordea Vardagspaket', service: 'Nordea', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-01-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-02-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-03-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-04-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-05-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-06-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-07-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-08-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-09-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-10-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-11-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-12-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-01-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-02-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-03-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-04-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-05-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-06-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-07-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-08-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-09-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-10-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-11-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2018-12-02', cost: '99', description: 'Spotify', service: 'Spotify', type: 'monthly', comment: '', category: 7, recurrent: '' },
  { date: '2017-01-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-02-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-03-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-04-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-05-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-06-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-07-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-08-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-09-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-10-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-11-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-12-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-01-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-02-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-03-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-04-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-05-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-06-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-07-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-08-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-09-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-10-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-11-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2018-12-27', cost: '112', description: 'Unionen A-kassa', service: 'Unionen A-kassa', type: 'monthly', comment: '', category: 13, recurrent: '' },
  { date: '2017-01-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-02-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-03-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-04-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-05-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-06-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-07-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-08-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-09-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-10-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-11-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-12-27', cost: '2700', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-01-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-02-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-03-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-04-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-05-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-06-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-07-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-08-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-09-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-10-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-11-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2018-12-27', cost: '2816', description: 'Hyra', service: 'Fridshyddevägen', type: 'monthly', comment: 'Fridshyddevägen', category: 14, recurrent: '' },
  { date: '2017-05-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-06-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-07-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-08-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-09-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-10-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-11-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-12-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-01-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-02-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-03-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-04-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-05-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-06-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-07-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-08-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-09-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-10-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-11-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2018-12-09', cost: '61', description: 'Privata repositories', service: 'GitHub.com', type: 'monthly', comment: 'GitHUb', category: 7, recurrent: '' },
  { date: '2017-05-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-06-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-07-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-08-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-09-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-10-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-11-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-12-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-01-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-02-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-03-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-04-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-05-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-06-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-07-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-08-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-09-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-10-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-11-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2018-12-27', cost: '145', description: 'Mobiltelefon', service: 'Comviq', type: 'monthly', comment: 'Comviq', category: 7, recurrent: '' },
  { date: '2017-06-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-07-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-08-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-09-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-10-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-11-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2017-12-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-01-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-02-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-03-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-04-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-05-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-06-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-07-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-08-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-09-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-10-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-11-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
  { date: '2018-12-09', cost: '15', description: 'Backblaze B2', service: 'Backblaze', type: 'monthly', comment: 'Backblaze', category: 7, recurrent: '' },
];

export const dummy = 1;
